FROM tomcat

RUN apt update

RUN rm -rf /usr/local/tomcat/webapps 
RUN mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps

EXPOSE 8080

HEALTHCHECK --start-period=1s                                             \
            --interval=1s                                                 \
            --timeout=5s                                                  \
            --retries=33                                                  \
        CMD wget -q --spider http://127.0.0.1:8080 || exit 1
CMD ["catalina.sh", "run"]
